version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
sphinx:
  builder: html
  configuration: docs/conf.py
formats: all
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
