#!/bin/bash -eux

if [ $# = 0 ]; then
  BLACK_ARG=""
else
  BLACK_ARG=$*
fi

black -l 80 $BLACK_ARG \
  d3rlpy/models \
  d3rlpy/q_functions.py \
  d3rlpy/encoders.py \
  tests/models \
  tests/test_q_functions.py \
  tests/test_encoders.py
